### ISSUE TITLE
wp-hooks alternatives

### ISSUE THREAD

**Issue by szepeviktor** [widoz/event-listeners-collection#7]
Writing here as wp-hooks is archived.

- https://github.com/Dhii/wp-events [deprecated](https://github.com/Dhii/psr-14/issues/3#issuecomment-582006224)
- https://github.com/iron-bound-designs/psr-14-wp :)

**Comment by szepeviktor** [comment]
Coming soon https://github.com/inpsyde/wp-events by @inpsyde

**Comment by widoz** [comment]
I know that, my colleague is working on that solution. How do you know it? It's private repo.

**Comment by szepeviktor** [comment]
I've [been told](https://github.com/Dhii/psr-14/issues/3#issuecomment-582006224).
